function h=vPALM2_2d3d_visualization_gui(h,FIGH,FIGW)


top=FIGH-100;
toggle_size=[100, 20];
toggle_size_small=[60, 20];
slider_size=[60, 10];
edit_size=[45,25];

border_buffer_px=20; % in px
axis1_width_px=260; %440t
axis1_height_px=260;
axis2_width_px=500;
axis1_size=[1-axis2_width_px./FIGW-4*border_buffer_px./FIGW-axis1_width_px./FIGW 2*border_buffer_px./FIGH axis1_width_px./FIGW axis1_height_px/FIGH];
axis2_size=[1-axis2_width_px./FIGW-border_buffer_px./FIGW 2*border_buffer_px./FIGH axis2_width_px./FIGW axis2_width_px./FIGH];

hor_spacing=5;
ver_spacing=0;
displine=[0 40 70 95 120 145 170 195 230 260 275 320 350 380 400 420 440 460 480 500 520 540 560 580];
disprow=10+[0:30]*(toggle_size(1)+hor_spacing);
disprow_small=10+[0:30]*(toggle_size_small(1)+hor_spacing);

slider_x=10+[0:10]*(slider_size(1)+2*hor_spacing+edit_size(1));            

forecolor=[0 0 0];
textcolor=[0 0 0];
backgroundcolor=[1 1 1];
h.xlabelcolor=[ 0 0 0 ];
pushbackgroundcolor=[ .7 .7 .7 ];
checkbox_size=[130, 20];



h.xyplane = uicontrol(h.fig,'Style','pushbutton',...
                'String','XY',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(1) top-displine(1) toggle_size_small(1) toggle_size_small(2)]);
h.yzplane = uicontrol(h.fig,'Style','pushbutton',...
                'String','YZ',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(2) top-displine(1) toggle_size_small(1) toggle_size_small(2)]);
h.xzplane = uicontrol(h.fig,'Style','pushbutton',...
                'String','XZ',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(3) top-displine(1) toggle_size_small(1) toggle_size_small(2)]);
h.xyzplane = uicontrol(h.fig,'Style','pushbutton',...
                'String','XYZ',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(4) top-displine(1) toggle_size_small(1) toggle_size_small(2)]);
h.rotAZ = uicontrol(h.fig,'Style','pushbutton',...
                'String','rotAZ->>',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(1) top-displine(2) toggle_size_small(1) toggle_size_small(2)]);
h.rotEL = uicontrol(h.fig,'Style','pushbutton',...
                'String','rotEL->>',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(3) top-displine(2) toggle_size_small(1) toggle_size_small(2)]);
h.rotAZ_neg = uicontrol(h.fig,'Style','pushbutton',...
                'String','<<-rotAZ',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(2) top-displine(2) toggle_size_small(1) toggle_size_small(2)]);
h.rotEL_neg = uicontrol(h.fig,'Style','pushbutton',...
                'String','<<-rotEL',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow_small(4) top-displine(2) toggle_size_small(1) toggle_size_small(2)]);
