function h=vPALM2_gui_construction(h,FIGH,FIGW)
% M Nollmann, Sep 2015.
% Centre de Biochimie Structurale
% CNRS, 29 rue de Navacelles, Montpellier, France
%

%% initializations

top=FIGH-100;
toggle_size=[120, 20];
toggle_size_small=[60, 20];
slider_size=[60, 10];
edit_size=[45,25];

border_buffer_px=20; % in px
axis1_width_px=260; %440t
axis1_height_px=260;
axis2_width_px=500;

% axis1_size=[1-axis2_width_px./FIGW-4*border_buffer_px./FIGW-axis1_width_px./FIGW 2*border_buffer_px./FIGH axis1_width_px./FIGW axis1_height_px/FIGH];
axis1_size=[ 1-axis1_width_px./FIGW-4*border_buffer_px./FIGW 2*border_buffer_px./FIGH axis1_width_px./FIGW axis1_height_px/FIGH]

scrsz = get(0,'ScreenSize');
% axis2_size=[1-axis2_width_px./FIGW-border_buffer_px./FIGW 2*border_buffer_px./FIGH axis2_width_px./FIGW axis2_width_px./FIGH];
axis2_size=[scrsz(3)-axis2_width_px scrsz(4)-axis2_width_px axis2_width_px axis2_width_px]

hor_spacing=20;
ver_spacing=0;
displine=[-10:20:FIGH]%[-10 10 30 50 70 90 110 150 230 260 275 320 350 380 400 420 440 460 480 500 520 540 560 580 600 620 640 660];
disprow=10+[0:30]*(toggle_size(1)+hor_spacing);
disprow_small=10+[0:30]*(toggle_size_small(1)+hor_spacing);

slider_x=10+[0:10]*(slider_size(1)+2*hor_spacing+edit_size(1));            

forecolor=[0 0 0];
textcolor=[0 0 0];
backgroundcolor=[1 1 1];
h.xlabelcolor=[ 0 0 0 ];
pushbackgroundcolor=[ .7 .7 .7 ];
checkbox_size=[130, 20];

%% axes

h.axes1 = axes('Parent',h.MainFig,'Position',axis1_size);

h.MainFigure3D=figure('Position',axis2_size,'Visible','on','CloseRequestFcn',@newclosefunction);

h.axes2 = axes('Parent',h.MainFigure3D);


%% Status and display
% pure text
h.txt_vPALM = uicontrol(h.MainFig,'Style','text',...
                'String','vPALM v2.3',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor','b',...
                'FontSize',25,...
                'Position',[10 top-displine(1) 220 80]);
h.txt_vPALM = uicontrol(h.MainFig,'Style','text',...
                'String','Nollmann group, Centre de Biochimie Structurale, CNRS',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor','k',...
                'FontSize',13,...
                'Position',[220 top-displine(1) 220 80]);
            
h.filename_static = uicontrol(h.MainFig,'Style','text',...
                'String','filename:',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(4) top-displine(2) 100 20]);
h.filename = uicontrol(h.MainFig,'Style','text',...
                'String','none yet',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(4) top-displine(2) 300 20]);
h.status = uicontrol(h.MainFig,'Style','text',...
                'String','-',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(5) top-displine(3)-15 160 20]);
h.status_txt = uicontrol(h.MainFig,'Style','text',...
                'String','status',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[disprow(4) top-displine(3)-15 30 20]);
h.Nparticles_txt = uicontrol(h.MainFig,'Style','text',...
                'String','0',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(5) top-displine(4)-35 100 20]);
h.Nparticles_label_txt = uicontrol(h.MainFig,'Style','text',...
                'String','# particles:',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[disprow(4) top-displine(4)-35 80 20]);
         

            
%% loads and saves
%title
h.load_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Load/save',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',16,...
                'HorizontalAlignment','left',...
                'Position',[10 top-displine(1) 120 20]);
            
%pushbuttons
h.push_load_file = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Load Analysis',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow(1) top-displine(2) toggle_size(1) toggle_size(2)]);
h.save_data = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Save data',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow(1) top-displine(3)  toggle_size(1) toggle_size(2)]);

h.save_PALMvis = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Save ViSP',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow(1) top-displine(4) toggle_size(1) toggle_size(2)]);
            
        
% checkboxes
h.chb_data_loaded = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Data loaded',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(2) top-displine(3) checkbox_size(1) checkbox_size(2)]);            
            
h.chb_image_load = uicontrol(h.MainFig,'Style','checkbox',...
                'String','load image?',...le
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(2) top-displine(4) checkbox_size(1) checkbox_size(2)]);            
h.chb_saveappend = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Append?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(2) top-displine(5) checkbox_size(1) checkbox_size(2)]);            
h.chb_collate = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Collate files?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(2) top-displine(6) checkbox_size(1) checkbox_size(2)]);            

            
%popup menus
h.load_options = uicontrol(h.MainFig,'Style','popupmenu',...
                'String','0',...
                'ForegroundColor',[.1 .1 .1],...
                'String',{'vPALM','qPALM','PALMcbs','MTT','rapidStorm','micromanager-2D','micromanager-3D','ThunderSTORM'},...
                'Value',8,'Position',[disprow(2) top-displine(2) 130 20]);
%% Parameters
parameters_top_col=7;
parameters_left_row=1;
% title
h.Parameters_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Parameters',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',16,...
                'HorizontalAlignment','left',...
                'Position',[disprow(parameters_left_row) top-displine(parameters_top_col) 120 20]);   
%txt
h.pixelsize_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Pixel size, nm',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(parameters_left_row) top-displine(parameters_top_col+1) 100 20]);
h.stepsize_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Step size, nm',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(parameters_left_row) top-displine(parameters_top_col+2) 100 20]);
h.Nvoxels_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Voxel size, nm',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[disprow(parameters_left_row) top-displine(parameters_top_col+3) 80 20]);  
%edits            
h.pixelsize = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','107',...
                'Visible','on',...
                'Position',[disprow(parameters_left_row+1) top-displine(parameters_top_col+1) edit_size(1) edit_size(2)]);            
h.stepsize = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','24',...
                'Visible','on',...
                'Position',[disprow(parameters_left_row+1) top-displine(parameters_top_col+2) edit_size(1) edit_size(2)]);            
h.Nvoxels = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','200',...
                'Visible','on',...
                'Position',[disprow(parameters_left_row+1) top-displine(parameters_top_col+3) edit_size(1) edit_size(2)]);            

%% Analysis
%title
analysis_top_col=12;
h.Analysis_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Analysis',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',16,...
                'HorizontalAlignment','left',...
                'Position',[10 top-displine(analysis_top_col) 100 20]);   
%pushbuttons
h.calc_res = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Calc Resolution',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[slider_x(1) top-displine(analysis_top_col+5) toggle_size(1) toggle_size(2)]);

% text
h.stats_slider_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Statistics:',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[slider_x(1) top-displine(analysis_top_col+1) 80 20]);

h.colorcode_slider_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Zaxis/Color',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[slider_x(1) top-displine(analysis_top_col+2) 100 20]);
h.analysis_slider_txt = uicontrol(h.MainFig,'Style','text',...
                'String','+ Analysis',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[slider_x(1) top-displine(analysis_top_col+3) 80 20]);
    
% popup menus
h.stats = uicontrol(h.MainFig,'Style','popupmenu',...
                'String','0',...
                'ForegroundColor',[.1 .1 .1],...
                'String',{'N localizations','N local/pixel','density','dy','dx','dz','resolution','background','Intensity'},...
                'Value',1,'Position',[disprow(2) top-displine(analysis_top_col+1) 130 20]);
                        
h.zplotoption = uicontrol(h.MainFig,'Style','popupmenu',...
                'String','0',...
                'ForegroundColor',[.1 .1 .1],...
                'String',{'intensity','z','density','resolution','time'},...
                'Value',1,'Position',[disprow(2) top-displine(analysis_top_col+2) 130 20]);

h.analysis = uicontrol(h.MainFig,'Style','popupmenu',...
                'String','0',...
                'ForegroundColor',[.1 .1 .1],...
                'String',{'Cluster analysis','Trace analysis'},...
                'Value',1,'Position',[disprow(2) top-displine(analysis_top_col+3) 130 20]);

            
%% Plotting
plotting_top_col=12;
%title
h.Plotting_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Plotting',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',16,...
                'HorizontalAlignment','left',...
                'Position',[disprow(3) top-displine(plotting_top_col) 120 20]);   

%buttons
h.plot_localizations_3d = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Plot events 3D',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow(3) top-displine(plotting_top_col+1) toggle_size(1) toggle_size(2)]);
h.plot_localizations_2d = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Plot events 2D',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow(3) top-displine(plotting_top_col+2) toggle_size(1) toggle_size(2)]);
h.plot_reconstruction = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Plot reconstr',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow(3) top-displine(plotting_top_col+3) toggle_size(1) toggle_size(2)]);
h.plot_density = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Plot density',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[disprow(3) top-displine(plotting_top_col+4) toggle_size(1) toggle_size(2)]);
%text
h.reconst_pixelsize_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Reconst pixel size, nm',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(5) top-displine(plotting_top_col+3) 120 20]);
h.reconst_resolution_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Reconst resolution, nm',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'HorizontalAlignment','left',...
                'FontSize',10,...
                'Position',[disprow(5) top-displine(plotting_top_col+4) 120 20]);
%edits
h.stepsize_reconstruction = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','10',...
                'Visible','on',...
                'Position',[disprow(6) top-displine(plotting_top_col+3) edit_size(1) edit_size(2)]);            
h.resolution_reconstruction = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','25',...
                'Visible','on',...
                'Position',[disprow(6) top-displine(plotting_top_col+4) edit_size(1) edit_size(2)]);            

            
%check boxes
h.chb_fix_resolution = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Fix res?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(4) top-displine(plotting_top_col+1) checkbox_size(1) checkbox_size(2)]);            
h.chb_uniform_peaks = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Unif peaks?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(4) top-displine(plotting_top_col+2) checkbox_size(1) checkbox_size(2)]);            
h.chb_scalebar = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Scalebar?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(4) top-displine(plotting_top_col+3) checkbox_size(1) checkbox_size(2)]);            
h.chb_DIPimage = uicontrol(h.MainFig,'Style','checkbox',...
                'String','2D histogram',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',1,'Position',[disprow(4) top-displine(plotting_top_col+4) checkbox_size(1) checkbox_size(2)]);            
h.chb_loc_by_moment = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Loc. by moment?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',1,'Position',[disprow(4) top-displine(plotting_top_col+5) checkbox_size(1) checkbox_size(2)]);            

% popup menus
h.display3D = uicontrol(h.MainFig,'Style','popupmenu',...
                'String','0',...
                'ForegroundColor',[.1 .1 .1],...
                'String',{'scatter3','scatter density','surface','voxels'},...
                'Value',1,'Position',[disprow(5) top-displine(plotting_top_col+1) 130 20]);%16 1
h.Zcolormap = uicontrol(h.MainFig,'Style','popupmenu',...
                'String','0',...
                'ForegroundColor',[.1 .1 .1],...
                'String',{'jet','hot','HSV','gray','cool'},...
                'Value',1,'Position',[disprow(5) top-displine(plotting_top_col+2) 130 20]);% disprow(5) top-displine(4) 130 20

%% ROI and Drift
corrections_top_col=2;
corrections_left_row=19;
%text
h.Corrections_txt = uicontrol(h.MainFig,'Style','text',...
                'String','ROI and Drift',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',16,...
                'HorizontalAlignment','left',...
                'Position',[10 top-displine(corrections_left_row) 120 20]);   
h.offsetx_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Offset X',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[slider_x(3)-80 top-displine(corrections_left_row+4) 80 20]);
h.offsety_txt = uicontrol(h.MainFig,'Style','text',...
                'String','Offset Y',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',10,...
                'HorizontalAlignment','left',...
                'Position',[slider_x(3)-80 top-displine(corrections_left_row+5) 80 20]);  
            
            
% pushbuttons            
         
h.make_roi = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','make ROI',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[slider_x(1) top-displine(corrections_left_row+2) toggle_size(1) toggle_size(2)]);

h.reset_roi = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','reset ROI',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[slider_x(1) top-displine(corrections_left_row+3) toggle_size(1) toggle_size(2)]);
h.save_axes1 = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','save axes 1',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[slider_x(1) top-displine(corrections_left_row+4) toggle_size(1) toggle_size(2)]);
h.selectbeads = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Drift correction',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[slider_x(1) top-displine(corrections_left_row+5) toggle_size(1) toggle_size(2)]);

% checkbox
h.chb_drift_correction = uicontrol(h.MainFig,'Style','checkbox',...
    'String','Correct drift?',...
    'BackgroundColor',backgroundcolor,...
    'ForegroundColor',textcolor,...
    'Value',0,'Position',[disprow(corrections_top_col) top-displine(corrections_left_row+2) checkbox_size(1) checkbox_size(2)]);            

h.chb_Remove_beads = uicontrol(h.MainFig,'Style','checkbox',...
    'String','Remove beads?',...
    'BackgroundColor',backgroundcolor,...
    'ForegroundColor',textcolor,...
    'Value',0,'Position',[disprow(corrections_top_col) top-displine(corrections_left_row+3) checkbox_size(1) checkbox_size(2)]);            


% sliders

h.offsetx_slider = uicontrol(h.MainFig,'Style','slider',...
                'Max',10,'Min',-10,'Value',0,...
                'SliderStep',[0.05 0.2],...
                'Position',[disprow(3) top-displine(corrections_left_row+4) slider_size(1) toggle_size_small(2)]);  
h.offsety_slider = uicontrol(h.MainFig,'Style','slider',...
                'Max',10,'Min',-10,'Value',0,...
                'SliderStep',[0.05 0.2],...
                'Position',[disprow(3) top-displine(corrections_left_row+5) slider_size(1) toggle_size_small(2)]);  
          

%% 3d
T3d_top_col=2;
T3d_left_row=26;
%title
h.ThreeD_txt = uicontrol(h.MainFig,'Style','text',...
                'String','3D',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'FontSize',16,...
                'HorizontalAlignment','left',...
                'Position',[10 top-displine(T3d_left_row) 30 20]);   

% checkboxes
h.chb_plot3d = uicontrol(h.MainFig,'Style','checkbox',...
                'String','plot 3D?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',1,'Position',[disprow(T3d_top_col) top-displine(T3d_left_row+2) checkbox_size(1) checkbox_size(2)]);            
            
h.chb_cal_3d = uicontrol(h.MainFig,'Style','checkbox',...
                'String','3d cal?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(T3d_top_col) top-displine(T3d_left_row+3) checkbox_size(1) checkbox_size(2)]);            
h.chb_3dcalapplied = uicontrol(h.MainFig,'Style','checkbox',...
                'String','3D cal applied?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(T3d_top_col) top-displine(T3d_left_row+4) checkbox_size(1) checkbox_size(2)]);            


h.chb_voxels = uicontrol(h.MainFig,'Style','checkbox',...
                'String','Use voxels?',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'Value',0,'Position',[disprow(T3d_top_col) top-displine(T3d_left_row+5) checkbox_size(1) checkbox_size(2)]);            
% pushbuttons
h.cal_3d = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','3D calibration',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[slider_x(1) top-displine(T3d_left_row+2) toggle_size(1) toggle_size(2)]);
h.apply_3dcal = uicontrol(h.MainFig,'Style','pushbutton',...
                'String','Apply 3Dcalibration',...
                'BackgroundColor',pushbackgroundcolor,'ForegroundColor',forecolor,...
                'Value',1,'Position',[slider_x(1) top-displine(T3d_left_row+3) toggle_size(1) toggle_size(2)]);
         

           

%% Toolbar
set(h.MainFig, 'Toolbar', 'figure')


%% edit

h.Zplotoptionedit = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','1',...
                'Visible','off',...
                'Position',[1 1 edit_size(1) edit_size(2)]);            

h.AZangle = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','-37.5',...
                'Visible','off',...
                'Position',[1 1 edit_size(1) edit_size(2)]);            
h.ELangle = uicontrol(h.MainFig,'Style','edit',...
                'BackgroundColor',backgroundcolor,...
                'ForegroundColor',textcolor,...
                'String','30',...
                'Visible','off',...
                'Position',[1 1 edit_size(1) edit_size(2)]);   
            
            
function newclosefunction(hObject, eventdata)
disp('Remember to close this GUI using the main vPALM window!');


